### ISSUE TITLE
Dependency Optimization manifest key incorrect

### ISSUE THREAD

**Issue by paul-hansen** [TimJentzsch/cargo-bavy#11] opened 2022-08-20 00:31 UTC
Using cargo-bavy it generates this:
``` toml
["profile.dev"]
opt-level = 1

["profile.dev.package.\"*\""]
opt-level = 3
```
Which produces the following warnings: 
```
warning: unused manifest key: profile.dev
warning: unused manifest key: profile.dev.package."*"
```

It should be:
``` toml
[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
```

**Comment by TimJentzsch** [comment] 2022-08-20 07:28
This is a duplicate of #1 and has already been fixed with #8, it will be included in the next release :)

**Closed as not planned** 2022-08-20 07:28 UTC
Labels: bug

**Comment by paul-hansen** [comment] 2022-08-20 12:55
Nice! sorry for the duplicate, I should have seen that.

**Comment by TimJentzsch** [comment] 2022-08-20 13:28
No worries :)
